# Generated by Django 3.2.25 on 2024-09-04 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tagitem',
            old_name='product',
            new_name='content_type',
        ),
        migrations.DeleteModel(
            name='LikedItem',
        ),
    ]
